/*
 * Generates supabase/seed.sql from data/pets.js.
 *
 *   node tools/make_seed.mjs > supabase/seed.sql
 *
 * data/pets.js is the one place the pet records are written by hand, so the
 * SQL is derived from it rather than maintained alongside it — two copies of
 * Kotik's story would drift apart the first time either was edited.
 *
 * The output is idempotent: it upserts on `slug`, so re-running it after
 * editing data/pets.js updates the existing rows instead of failing on a
 * duplicate key.
 *
 * Needs no dependencies — data/pets.js only assigns onto `window`, so it can
 * be evaluated against a stub object.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { runInNewContext } from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const sandbox = { window: {} };
runInNewContext(readFileSync(join(root, 'data', 'pets.js'), 'utf8'), sandbox);

const pets = sandbox.window.PETS_SEED;
if (!Array.isArray(pets) || pets.length === 0) {
  console.error('data/pets.js did not define a non-empty window.PETS_SEED');
  process.exit(1);
}

/* Postgres string literal: double every embedded quote. Used for slugs and for
   the jsonb payload, both of which contain user-authored text. */
const quote = (value) => `'${String(value).replace(/'/g, "''")}'`;

const rows = pets.map((pet) => {
  const doc = { ...pet };
  /* These three live in real columns; leaving copies in `doc` would mean two
     sources of truth for the same value. */
  delete doc.slug;
  delete doc.published;
  delete doc.sortOrder;

  const tagIds = (pet.tags || [])
    .map((tag) => (typeof tag === 'string' ? tag : tag.id))
    .filter(Boolean);

  return '  (' + [
    quote(pet.slug),
    pet.published ? 'true' : 'false',
    Number(pet.sortOrder) || 0,
    `ARRAY[${tagIds.map(quote).join(', ')}]::text[]`,
    `${quote(JSON.stringify(doc))}::jsonb`
  ].join(', ') + ')';
});

process.stdout.write(`-- Generated by tools/make_seed.mjs from data/pets.js — do not edit by hand.
-- Regenerate with:  node tools/make_seed.mjs > supabase/seed.sql
--
-- Safe to run more than once: existing slugs are updated, new ones inserted.
-- Run supabase/schema.sql first.

insert into public.pets (slug, published, sort_order, tag_ids, doc)
values
${rows.join(',\n')}
on conflict (slug) do update set
  published  = excluded.published,
  sort_order = excluded.sort_order,
  tag_ids    = excluded.tag_ids,
  doc        = excluded.doc,
  updated_at = now();
`);
