/*
 * Generates supabase/seed.sql from data/pets.js.
 *
 *   node tools/make_seed.mjs > supabase/seed.sql
 *
 * data/pets.js is the one place records are written by hand, so the SQL is
 * derived from it rather than maintained alongside it — two copies of Kotik's
 * story would drift apart the first time either was edited.
 *
 * Output order matters: tags, curators and donation links are inserted before
 * pets, because a pet carries foreign keys pointing at them.
 *
 * The whole thing is idempotent — every statement upserts on a natural key, so
 * re-running it after editing data/pets.js updates rather than duplicating.
 *
 * Needs no dependencies: data/pets.js only assigns onto `window`, so it can be
 * evaluated against a stub object.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { runInNewContext } from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const sandbox = { window: {} };
runInNewContext(readFileSync(join(root, 'data', 'pets.js'), 'utf8'), sandbox);

const pets = sandbox.window.PETS_SEED;
const tags = sandbox.window.TAGS_SEED || [];
const curators = sandbox.window.CURATORS_SEED || [];
const donations = sandbox.window.DONATIONS_SEED || [];

if (!Array.isArray(pets) || pets.length === 0) {
  console.error('data/pets.js did not define a non-empty window.PETS_SEED');
  process.exit(1);
}

/* Postgres string literal: double every embedded quote. */
const quote = (value) => `'${String(value).replace(/'/g, "''")}'`;
const json = (value) => `${quote(JSON.stringify(value))}::jsonb`;
const orNull = (value) => (value ? quote(value) : 'null');

const out = [];

out.push(`-- Generated by tools/make_seed.mjs from data/pets.js — do not edit by hand.
-- Regenerate with:  node tools/make_seed.mjs > supabase/seed.sql
--
-- Safe to run more than once: existing records are updated, new ones inserted.
-- Run supabase/schema.sql first.
`);

/* ------------------------------------------------------------------ tags */
if (tags.length) {
  const rows = tags.map((tag) => {
    const label = {};
    for (const [key, value] of Object.entries(tag)) {
      if (key !== 'id' && value) label[key] = value;
    }
    return `  (${quote(tag.id)}, ${json(label)})`;
  });

  out.push(`insert into public.tags (id, label)
values
${rows.join(',\n')}
on conflict (id) do update set label = excluded.label;
`);
}

/* -------------------------------------------------------------- curators */
if (curators.length) {
  const rows = curators.map((c) => `  (${[
    quote(c.slug),
    json(c.name || {}),
    json(c.bio || {}),
    orNull(c.photo),
    json(c.photoAlt || {}),
    orNull(c.email),
    orNull(c.telegram),
    orNull(c.instagram),
    orNull(c.phone),
  ].join(', ')})`);

  out.push(`insert into public.curators (slug, name, bio, photo, photo_alt, email, telegram, instagram, phone)
values
${rows.join(',\n')}
on conflict (slug) do update set
  name       = excluded.name,
  bio        = excluded.bio,
  photo      = excluded.photo,
  photo_alt  = excluded.photo_alt,
  email      = excluded.email,
  telegram   = excluded.telegram,
  instagram  = excluded.instagram,
  phone      = excluded.phone,
  updated_at = now();
`);
}

/* --------------------------------------------------------- donation links */
if (donations.length) {
  const rows = donations.map((d) => `  (${[
    quote(d.slug),
    quote(d.url),
    json(d.label || {}),
    json(d.note || {}),
    orNull(d.qr),
  ].join(', ')})`);

  out.push(`insert into public.donation_links (slug, url, label, note, qr)
values
${rows.join(',\n')}
on conflict (slug) do update set
  url        = excluded.url,
  label      = excluded.label,
  note       = excluded.note,
  qr         = excluded.qr,
  updated_at = now();
`);
}

/* ------------------------------------------------------------------ pets */
const petRows = pets.map((pet) => {
  const doc = { ...pet };
  /* These live in real columns; a copy inside `doc` would be a second,
     silently diverging source of truth. */
  delete doc.slug;
  delete doc.published;
  delete doc.sortOrder;
  delete doc.curatorSlug;
  delete doc.donationSlug;

  const tagIds = (pet.tags || [])
    .map((tag) => (typeof tag === 'string' ? tag : tag.id))
    .filter(Boolean);
  doc.tags = tagIds;

  /* Sub-selects rather than hard-coded uuids: the ids are generated by the
     database, so this file cannot know them, and looking them up by slug keeps
     the seed runnable against any project. */
  const curatorRef = pet.curatorSlug
    ? `(select id from public.curators where slug = ${quote(pet.curatorSlug)})`
    : 'null';
  const donationRef = pet.donationSlug
    ? `(select id from public.donation_links where slug = ${quote(pet.donationSlug)})`
    : 'null';

  return `  (${[
    quote(pet.slug),
    pet.published ? 'true' : 'false',
    Number(pet.sortOrder) || 0,
    `ARRAY[${tagIds.map(quote).join(', ')}]::text[]`,
    curatorRef,
    donationRef,
    json(doc),
  ].join(', ')})`;
});

out.push(`insert into public.pets (slug, published, sort_order, tag_ids, curator_id, donation_id, doc)
values
${petRows.join(',\n')}
on conflict (slug) do update set
  published   = excluded.published,
  sort_order  = excluded.sort_order,
  tag_ids     = excluded.tag_ids,
  curator_id  = excluded.curator_id,
  donation_id = excluded.donation_id,
  doc         = excluded.doc,
  updated_at  = now();
`);

process.stdout.write(out.join('\n'));
